# Manifest for Flavornet odor descriptors dataset
[source]
doi = "https://www.flavornet.org/"
title = "Flavornet and human odor space"
authors = "T. Acree, H. Arn"
extra = "Flavornet by Terry Acree & Heinrich Arn, http://www.flavornet.org, © Datu Inc., 2004."

[raw]
LICENSE = ""

[processed]
main.py = "Processing workflow. Data is scraped here directly from the Flavornet website to created the output files below."
molecules.csv = "Information about odorant molecules used."
behavior.csv = "Odor labels for each molecule (all labels semicolon separated in single column)."