# Manifest for Leon et al, 2009 data
[source]
doi = "10.1002/cne.22046"
url = "https://onlinelibrary.wiley.com/doi/10.1002/cne.22046"
title = "Spatial representations of odorants in olfactory bulbs of rats and mice: Similarities and differences in chemotopic organization"
authors = "BA Johnson, Zhe X, SS Ali, M Leon"
tags = "rodent;imaging;olfactoryBulb"

[raw]
"raw/*.csv" = "folder w/ glomerular activity maps (~550) as .png" 

[parsed]
"csvs/*.csv" = "folder with glomerular acivity maps in .csv format; filename are stimulus ID for each stimulus (pointed to by 'behavior.csv')"

[processed]
"molecules.csv" = "Information about odorant molecules used"
"stimuli.csv" = "Table of stimuli (odorants), corresponding CIDs, and experimental conditions (conc., duration, etc)"
"behavior_1.csv" = "Pointers to .csv file for each stimulus's glomerular activity map"
"behavior_2.csv" = "Ranking the ventral activity of odorant stimuli given by data in CSV files"

[code]
"main.py" = "Processing workflow"
"ventrality_ranking.ipynb" = "Jupyter notebook for calculating ventrality rankings"

