# Manifest for Leon et al, 2009 data
[source]
doi = "10.1002/cne.22046"
url = "https://onlinelibrary.wiley.com/doi/10.1002/cne.22046"
title = "Spatial representations of odorants in olfactory bulbs of rats and mice: Similarities and differences in chemotopic organization"
authors = "BA Johnson, Zhe X, SS Ali, M Leon"
tags = "rodent;imaging;olfactoryBulb"

[raw]
"Glomerular archive/ccc copy" = "folder w/ glomerular activity maps (~550) as .png" 

[processed]
"main.py" = "Processing workflow"
"molecules.csv" = "Information about odorant molecules used"
"identifiers.csv" = "Table of stimuli (odorants), corresponding CIDs, and experimental conditions (conc., duration, etc)"
"imaging.csv" = "Table of stimuli (odorants), and paths to disk for fetching corresponding .csv files (i.e. the glomerular images)"
"csvs/*.csv" = "CSV files of the glomerular maps (pointed to by 'imaging.csv')"
