# Manifest for FooDB dataset
[source]
doi = "https://foodb.ca/"
title = "FooDB Odor Dataset"
authors = ""
extra = ""

[raw]
compounds.csv = "Scraped list of compounds in database with identifiers for fetching CIDs"
properties.csv = "Full scrape of properties for each compound"
LICENSE = "FooDB is offered to the public as a freely available resource. Use and re-distribution of the data, in whole or in part, for commercial purposes requires explicit permission of the authors and explicit acknowledgment of the source material (FooDB) and the original publication (see below). We ask that users who download significant portions of the database cite the FooDB paper in any resulting publications. For commerical licence, please consult with tarassov@ualberta.ca (Oxana)."

[processed]
main.py = "Processing workflow"
molecules.csv = "Information about molecules used"
physics.csv = "Physicochemical properties of molecules"